### ISSUE TITLE
An error occurred with sendgrid/php-http-client version 3.14.0

### ISSUE THREAD

**Issue by oddmutou** [Iandenh/cakephp-sendgrid#24]
An error occurred and the email could not be sent. :cry: 

sendgrid/php-http-client: 3.14.0
cakephp/cakephp: 3.9.8

```
2021-04-05 17:09:28 Error: [SendGrid\Mail\TypeException] "$bccEmails" must be an array. Got:  (/foo/bar/vendor/sendgrid/sendgrid/lib/helper/Assert.php:151)
#0 /foo/bar/vendor/sendgrid/sendgrid/lib/helper/Assert.php(238): SendGrid\Helper\Assert::isArray(NULL, 'bccEmails', '"$bccEmails" mu...')
#1 /foo/bar/vendor/sendgrid/sendgrid/lib/mail/Mail.php(528): SendGrid\Helper\Assert::minItems(NULL, 'bccEmails', 1)
#2 /foo/bar/vendor/iandenh/cakephp-sendgrid/src/Mailer/Transport/SendgridTransport.php(50): SendGrid\Mail\Mail->addBccs(NULL)
#3 /foo/bar/vendor/cakephp/cakephp/src/Mailer/Email.php(2149): SendgridEmail\Mailer\Transport\SendgridTransport->send(Object(App\Mailer\EmailWrapper))
#4 ... (Omitted)
```

**Comment by oddmutou** [comment]
im realy sorry :bow: 

i used `2.0.0-beta5`...

i confirmed working in `2.0.0`.
https://github.com/Iandenh/cakephp-sendgrid/commit/129937e81703d7504ea1707fd0b23babf9c8b606
